IHP-GmbH/IHP-Open-PDK

- ihp-sg13g2/libs.ref/sg13g2_stdcell/lef/sg13g2_stdcell.lef
OpenROAD-flow-scripts and potentially other open-source flows use the lef `CLASS`  of cells to find antenna cells and fillers. This pull request improves compatibility with OpenROAD-flow-scripts by allowing it to automatically find the PDK's antenna cell and fillers.
> Use more specific lef class for antenna and filler cells

- ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2.lydrc
(reopened to point to `dev` branch)
This is a very small change to check whether `main_window` is valid before trying to get the current view. This allows the script to be run in batch mode (`klayout -zz -r sg13g2.lydrc <design>.gds`) without GUI. This is useful to run the DRC check in a script (for example as part of OpenROAD-flow-scripts) or on a remote server.
> Allow running KLayout DRC script without GUI

- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_moshv_mod.lib
- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_moshv_parm.lib
- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_moslv_mod.lib
- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_moslv_parm.lib
Fixes #25 
As mentioned in the discussion, this fix is not ideal, but it seems this is how the original spectre SG13G2 model extractors did it. One main open question is the parameter `m`, which is used in the scaling of the PSP model parameter `vfbo`.
This can not be verified at the moment since in the current available measurements there are no multi-finger device measurements present.
> removed the mfact parameter and implemented m properly

- ihp-sg13g2/libs.tech/xschem/README.md
- ihp-sg13g2/libs.tech/xschem/install.py
`install.py` script was provided in order to compile and copy PSP103 model into default location for simulation.
> Xschem configuration

- ihp-sg13g2/libs.tech/qucs/examples/dc_hv_nmos.sch
- ihp-sg13g2/libs.tech/qucs/examples/dc_hv_pmos.sch
- ihp-sg13g2/libs.tech/qucs/examples/dc_lv_nmos.sch
- ihp-sg13g2/libs.tech/qucs/examples/dc_lv_pmos.sch
- ihp-sg13g2/libs.tech/qucs/examples/symbols.sch
- ihp-sg13g2/libs.tech/qucs/user_lib/IHP_PDK_nonlinear_components.lib
Changes in `ihp-sg13g2/libs.tech/qucs/user_lib/IHP_PDK_nonlinear_components.lib` which remove `mfact` and add `m` parameter support (parallel devices). Also respective example test cases in `ihp-sg13g2/libs.tech/qucs/examples/` were updated .
> Qucs-S mosfets symbols and related examples updated to support m parameter 

- ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/sealring_code.py
- ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/sg13g2_tech.json
After filler metal got removed, the Passiv layer was placed at the edge of the sealring and, therefore, also at the edge of the die. Add a configurable EdgeSeal.boundary layer to the sealring to fill the gap between the sealring and die edge with metal fill.
Screenshot of the sealring with 25um distance to  Passiv (now default).
> libs.tech: klayout: tech: Add EdgeSeal.boundary to sealring

- ihp-sg13g2/libs.tech/klayout/tech/scripts/sealring.py
This script can be called in Klayout's batch mode and generates a GDS file with a sealring included. The width and height of the ring are configurable via arguments.
Example call:
klayout -n sg13g2 -zz -r sealring.py \
-rd width=1300.0 -rd height=1300.0 \
-rd output=macros/sealring.gds.gz
> libs.tech: klayout: Add Python script to generate Sealring files

- ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_density_report.lym
Global min./max. Metal(n) density values are 35% and 60%. The previous 25% and 75% are only valid for 800x800 chip areas.
> libs.tech: klayout: Fix Metal density min/max values

- ihp-sg13g2/libs.tech/klayout/tech/drc/MissingRules_maximal.md
- ihp-sg13g2/libs.tech/klayout/tech/drc/README.md
- ihp-sg13g2/libs.tech/klayout/tech/drc/README_maximal.md
- ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_maximal.lydrc
- ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc
- maximal DRC script supports ~75% of rules
- rename DRC script parameters for OpenROAD compatibility - logfile -> log_file - gdsfile -> in_gds - outfile -> report_file
- DRC script parameter "cell" is now optional
- output number of DRC errors at the end
- DRC script no longer depends on layout dbu - all lengths are given in micrometers
- add limits to rule descriptions, e.g., "Min. GatPoly width = 0.13"
There are many DRC errors for rules `pSD.d` and `pSD.d1` in our large test layout. It's possible we misunderstood the rules. Please check before merging.
This pull request includes a solution for #113
> Update KLayout DRC scripts

- ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_density_report.lym
Tabs are shown differently in Klayout's macro tool and command line. Sometimes it looks really odd. Spaces give a better result.
> libs.tech: klayout: macros: Fix intentation

- ihp-sg13g2/libs.tech/klayout/tech/sg13g2.lyt
Removing reference to merged.lef which does not exist.
Fixes NA
> Remove merged.lef from klayout setup

- ihp-sg13g2/libs.tech/klayout/tech/sg13g2.lyt
- ihp-sg13g2/libs.tech/klayout/tech/sg13g2.map
OpenROAD requires the sg13g2.map file to correctly place each layer. Fix this here to not overwrite manually changes in OpenROAD-Flow-Scripts.
> libs.tech: Klayout: tech: Add layer map

- ihp-sg13g2/libs.tech/xschem/xschemrc
Hello! I would like to propose a change to the `xschemrc` file.
Currently, the standard symbols are added via `append XSCHEM_LIBRARY_PATH ${XSCHEM_SHAREDIR}/xschem_library`.
This works, but is not the full path to the standard symbols, consequently the symbols have `devices/` in their symbol references. This has no advantages and is not compatible with the default xschem setup. This prevents, for example, the sharing of simple testbenches without correcting the paths.
A fix has already been made for Sky130 and submitted to gf180mcu:
- https://github.com/StefanSchippers/xschem_sky130/commit/0597d6cd26ad460d3f4d689f9e6a11f33dc262ff
- https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/pull/48
Here, the full path to the standard symbols was added before the existing one, so …
> Update path to standard symbols

- .gitmodules
- ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/__init__.py
- ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/pypreprocessor.py
-implemented 'conditional compilation' for PyCell code, see
documentation in ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/__init__.py
> Klayout PyCell integration

- ihp-sg13g2/libs.tech/xyce/models/sg13g2_hbt_mod.lib
For easier usage without need to compile Verilog-A code we use the Xyce build-in model for npn13G2 devices.
Because of outdated psp version 103.4 and missing if/then/else capabilities in netlist syntax this is not possible for MOSlv and MOShv devices.
> use Xyce vbic build-in model instead Verilog-A model

- ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v
The input and output definition in the Verilog specify block were positioned in the wrong order (output to input). Change and also implement the tri-state better.
Fixes #208
> iho-sg13g2: libs.ref: sg13g2_io: verilog: Fix specify syntax

- ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/__init__.py
This function has a hard depdendency to 'psutil' but is only required when IHP_PYCELL_LIB_PRINT_PROCESS_TREE is set. Move 'getProcessNames' inside the if block to allow using this PDK without 'psutil' installed.
Fixes #226
> ihp-sg13g2: libs.tech: klayout: python: Move getProcessNames()

- ihp-sg13g2/libs.tech/klayout/README.md
- ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/__init__.py
-reduced psutil-dependency to the use of conditional PyCell compilation
Fixes #226 >
> Fix https://github.com/IHP-GmbH/IHP-Open-PDK/issues/226

- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_moshv_mod.lib
- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_moslv_mod.lib
Fixes #164
This PR solves the problem in wrong RG calculation with a high impact to correct noise calculation in rfmode=1 for multifinger lv and hv MOS devices.
> new instantiation scheme for lv and hv MOS to fix bug in RG calculation

- ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/sealring_code.py
The `w` and `l` are swapped so if you generate a non-square Seal Ring, then that layer is rotated 90 deg vs the rest of the ring.
> libs.tech/klayout: Fix the seal ring pcell EdgeSeal/boundary

- ihp-sg13g2/libs.tech/klayout/tech/lvs/rule_decks/mos_derivations.lvs
> Ignoring dummy trans from being recognized in LVS

- ihp-sg13g2/libs.tech/xyce/models/sg13g2_hbt_mod.lib
This PR introduces 5 terminal versions of  `HBT` devices.
The change is similar to the one introduced in ngspice in PR #261 
> [!CAUTION]
> In order to support Xyce model level was changed from 9 to 12
Device | 4 terminal subcircuit name | 5 terminal subcircuit name
---------- | ---------- | ------ 
npn13G2      | npn13G2       | npn13G2_5t 
npn13G2l     | npn13G2l       | npn13G2l_5t 
npn13G2v      | npn13G2v       | npn13G2v_5t
> HBT model card update introducing 5 teminal devices

- ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/__init__.py
- ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/pypreprocessor.py
The variable `preProcessor`  is already defined by the import statement:
```python
from pypreprocessor.pypreprocessor import preprocessor as preProcessor
```
so the later redefinition can be removed. As a result, the symbolic link `pypreprocessor.py` can also be deleted.
> PyCells: Remove unneeded code

- ihp-sg13g2/libs.tech/xschem/sg13g2_tests_xyce/IHP_testcases.sch
- ihp-sg13g2/libs.tech/xschem/sg13g2_tests_xyce/ac_rfmim_cap.sch
- ihp-sg13g2/libs.tech/xschem/sg13g2_tests_xyce/ac_rfmim_cap.sym
- ihp-sg13g2/libs.tech/xyce/models/capacitors_mod.lib
This PR adds `xyce` support for `RF MiM` 3 terminal capacitor device.  
1. Still the code needs to be fixed in order to support `if-else` statements (Verilog-A model)
2. A `xschem` test case for `xyce` was added
> RF MiM capacitor support 

- ihp-sg13g2/libs.tech/klayout/tech/lvs/rule_decks/res_connections.lvs
- ihp-sg13g2/libs.tech/klayout/tech/lvs/rule_decks/res_derivations.lvs
> Improving resistor connections for LVS for proper detection with poly conn

- ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_filler_Metal.lym
Metal fill was a little bit too low for M1 and too high for M3-5.
Fixes #<issue_number_goes_here>
> ihp-sg13g2: libs.tech: klayout: tech: macros: Adjust metal filler

- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_hbt_mod.lib
Fixes #309
The switch sw_nqs is a parameter of the npn13G2 subckt. Default is 0 - setting it to 1 enables the NQS model in vbic.
In schematic an appropriate symbol is needed.
> provide a switch for vbic NQS effect

- ihp-sg13g2/libs.tech/xschem/sg13g2_pr/annotate_fet_params.sym
- ihp-sg13g2/libs.tech/xschem/sg13g2_tests/dc_hv_nmos.sch
- ihp-sg13g2/libs.tech/xschem/sg13g2_tests/dc_hv_pmos.sch
- ihp-sg13g2/libs.tech/xschem/sg13g2_tests/dc_lv_nmos.sch
- ihp-sg13g2/libs.tech/xschem/sg13g2_tests/dc_lv_pmos.sch
- ihp-sg13g2/libs.tech/xschem/xschemrc
Implements @hpretl [request](https://open-source-silicon.slack.com/archives/C017P3RAD42/p1740812343257639?thread_ts=1740791679.438969&cid=C017P3RAD42)
Added symbol: `sg13g2_pr/annotate_fet_params.sym`
Shows `gm, gds, vth, vdss, cgg, cgdol, cgsol` and `ft` (calculated from previous parameters) for the transistor it is linked to (via a `ref=Mx` attribute).
`sg13g2_tests/dc_*v_*mos.sch` test cases changed to use it. 
Helper procedures added to xschemrc
IHP specific menu entry added with 3 entries:
1. **Create FET .save file**: this creates a file with .save instructions, so that all data is available in the raw file. Just add a .include line of the generated file in the testbench. This is done in the `sg13g2_tests/dc_*v_*mos.sch` test cases 
2. **Add models symbol**. This simple entry places …
> Annotation of key FET parameters

- ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_maximal.lydrc
Allow to disable the Latch-up rules via a KLayout parameter to not check against them.
> Make Latch-up rules optional

- ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_maximal.lydrc
- ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc
- checking for a density >0 creates errors for empty layers
- error markers are clamped to the chip area
- new option `tiles_stay_inside` that moves tiles back into the chip
area if they overlap the chip boundary
Fixes issuees #391 and #404
> DRC: Update density checks

- ihp-sg13g2/libs.tech/ngspice/models/capacitors_stat.lib
- ihp-sg13g2/libs.tech/ngspice/models/resistors_stat.lib
- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_hbt_stat.lib
- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_moshv_stat.lib
- ihp-sg13g2/libs.tech/ngspice/models/sg13g2_moslv_stat.lib
Statistical variations got now more meaningful parameter name num_sigmas instead mc_ok. All lib's are unified, also the entries for resistors_stat.lib.
Selection of statistical simulation model have to done by .lib entry with prepended `_stat` in the name, e.g. `.lib sg13g2_moslv_stat`.
There is no need for setting mc_ok=1 on top level circuit.
> introduce num_sigmas instead mc_ok for statistical models

- ihp-sg13g2/libs.tech/xschem/sg13g2_pr/ntap1.sym
- ihp-sg13g2/libs.tech/xschem/sg13g2_pr/ptap1.sym
This PR changes the pin order in the netlist  streamed out from xschem.
For `ptap1` the lvs netlist is annotated as follows
```
R1 GND sub! ptap1 A=6.084e-13 P=3.12e-06
```
For `ntap1` the lvs netlist is annotated as follows
```
R1 vdd well ntap1 A=6.084e-13 P=3.12e-06
```
> Ptap1 and ntap1 devices pin change in xschem symbols

- ihp-sg13g2/libs.tech/xschem/xschemrc
> Calculation of OP param rin in HBT annotation updated

- ihp-sg13g2/libs.tech/ngspice/models/capacitors_mod_mismatch.lib
- ihp-sg13g2/libs.tech/ngspice/models/cornerCAP.lib
- ihp-sg13g2/libs.tech/ngspice/models/cornerHBT.lib
- ihp-sg13g2/libs.tech/ngspice/models/cornerMOShv.lib
- ihp-sg13g2/libs.tech/ngspice/models/cornerMOSlv.lib
- ihp-sg13g2/libs.tech/ngspice/models/cornerRES.lib
- ihp-sg13g2/libs.tech/ngspice/models/resistors_mod_mismatch.lib
- ihp-sg13g2/libs.tech/qucs/user_lib/IHP_PDK_nonlinear_components.lib
Fixes #496
This PR fixes the problem of inconsistent results for repeated runs with identically circuit.
The drawback is that the user have to specify the dedicated library entry if he want execute mismatch simulations.
E.g. in case for hbt:
.LIB "$PDK_ROOT/$PDK/libs.tech/ngspice/models/cornerHBT.lib" hbt_typ_mismatch
or (dependent from .spinit)
.LIB cornerHBT.lib" hbt_typ_mismatch
The option to switch on/off mismatch simulation for selected devices in the circuit is preserved. Default setting is still "on".
> Fix mismatch bug #496

- ihp-sg13g2/libs.tech/klayout/tech/d25/sg13g2_beol.lyd25
This PR provides a feature inspect the metal stack using klayout 2.5 D viewer.
It was originally provided by `Volker Muehlhaus`. This functionality can be run from 
the `SG13G2 PDK` menu using `BEOL 2.5D Viewer` button:
Example view:
> BEOL inspection support using 2.5 klayout viewer

- ihp-sg13g2/libs.tech/klayout/tech/lvs/rule_decks/general_derivations.lvs
The holes function returns the inside of donut shapes. The seal ring is a ptap that surrounds the entire chip. When the sealring is included, the entire chip becomes `ptap_holes`. This change ignores the sealring ptap when calculating ptap_holes. For designs without the sealring, there is no change. 
Warning: Use of the holes function in LVS can cause unexpected side-effects when macros have enclosing tap rings.
Fixes #498
- [?] Tests pass <- This change is part of a larger set of changes that I'm working on for the TO_Apr2025 shuttle tests. The larger set of changes is still being tested, but this specific change has been verified to solve the issue above.
> Changed ptap_holes calculation

- ihp-sg13g2/libs.tech/xschem/sg13g2_tests_xyce/dc_hbt_13g2.sch
- ihp-sg13g2/libs.tech/xyce/models/sg13g2_hbt_mod.lib
> HBT selft enabled also for XYCE simulator

- ihp-sg13g2/libs.ref/sg13g2_io/spice/sg13g2_io.spi
- ihp-sg13g2/libs.tech/ngspice/.spiceinit
Modifications in IO spice netlist in order to support 3 terminal resistors introduced in this PR #563 and #572.  
Also a reference to this library was added in the `ngspice`  `.spiceinit` config file.
The changes introduce `sub!` global net as followis:
```
XR1 pad core sub! rppd l=2.0um w=1.0um
``` 
If using `xschem`  a symbol of `sub!` can be added and connected to the `GDN/VSS` in your testbench. 
This will result in the annotation of a global net `sub!` in the netlist. 
```
V5 GND sub! 0
.GLOBAL GND
.GLOBAL sub!
```
This PR addresses the issue #574
> Modifications in IO spice netlist in order to support 3 terminal resistor model

- ihp-sg13g2/libs.tech/xschem/sg13g2_pr/sg13_svaricap.sym
- ihp-sg13g2/libs.tech/xschem/xschem-drc
DRC checks for `xschem` added.
Symbol for `S-Varicap` slightly modified.
This PR addresses the issue #577
> Xschem DRC checks added for S-Varicap device.

- ihp-sg13g2/libs.tech/librelane/config.tcl
Update the path to the LVS script as changed two weeks ago in: https://github.com/IHP-GmbH/IHP-Open-PDK/commit/d7e173a0511d09fe807e70d5d07b597d28a3b987
> libs.tech/librelane: Update path to LVS script

- ihp-sg13g2/libs.tech/magic/ihp-sg13g2.tech
Corrected the magic tech file "lef" section, which was missing definitions for Via obstructions.  The missing obstruction layers resulted in incorrect reading of the LEF views of the I/O cells when doing "lef read" in magic, causing pins in the I/O cells to be shorted.
Fixes #623
Nothing needs changing in the README file, although I just noticed that the README file does not include Magic and netgen as supported tools;  I will fix this in an upcoming unrelated pull request.
Signed-off-by: R. Timothy Edwards <tim@opencircuitdesign.com>
> Corrected the magic tech file "lef" section, which was missing definitions for Via obstructions.

- ihp-sg13g2/libs.tech/klayout/tech/scripts/sealring.py
Hi all,
When using the sealring with ORFS digital designs, the design is located at (0,0) and the sealring needs to be moved.
(At least this is what the [masked-aes-tapeout](https://github.com/HEP-Alliance/masked-aes-tapeout) README suggests. I used that repo as a reference, as suggested in the Digital Design Workshop in February. I hope this is still the up-to-date way to do things :smile: )
This commit implements additional offset parameters in the `sealring.py` script. Using these parameters the final sealring can be generated directly to avoid the manual moving step.
BTW: There's also an issue in this line:
```python
pcell = layout.add_pcell_variant(lib, pcell_decl.id(), {'w': f'{width}u', 'l': f'{heigth}u'})
```
It actually confuses width and height. But should this be fixed in the …
> sealring.py: Add offset options

- ihp-sg13g2/libs.tech/xschem/sg13g2_pr/nmoscl_2.sym
- ihp-sg13g2/libs.tech/xschem/sg13g2_pr/nmoscl_4.sym
- ihp-sg13g2/libs.tech/xschem/sg13g2_tests/dc_esd_nmos_cl.sch
- ihp-sg13g2/libs.tech/xschem/sg13g2_tests_xyce/dc_esd_nmos_cl.sch
Fixes #594 
Port order changed for `xschem` symbols.
> nmos_cl symbols for xschem updated

- ihp-sg13g2/libs.tech/klayout/tech/drc/rule_decks/antenna.drc
- ihp-sg13g2/libs.tech/klayout/tech/drc/run_drc.py
- ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_drc.lym
- Fixes #656 
- Cleaning up the antenna rule deck placeholder; this file will be updated once antenna checks are supported.
- Fixes #654
- Supporting using spaces in the drc options for GUI run
> Klayout DRC Updates

- ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_filler_Metal.lym
Currently, the input checks for metal filler distances are all against `distances['distance_m1']`.
This commit fixes the checks to validate each respective metal layer's distance.
> klayout(metal fill): fix minimum distance check for metal layers

- ihp-sg13g2/libs.tech/ngspice/models/diodes.lib
Regarding ngspice manual 2.11.1 unquoted expressions in param statements, instance and model parameters are not allowed.
The reliable way is to single quote them.
> remove spaces in expressions if they are not quoted
