ihp-sg13g2/libs.tech/klayout/tech/sg13g2.lyt
This will allow to use 'Tools->Trace Net' and 'Tools->Trace All Nets'
=> Add connectivity information to the klayout technology file

ihp-sg13g2/libs.tech/klayout/python/cni/pointlist.py, ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/cmim_code.py, ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/sg13g2_tech.json, ihp-sg13g2/libs.tech/klayout/sg13g2_tests/pycell_test.py
-PointList.compress() shall compress the current instance, fixed
-fixed unintendend delivery of cmim-changes
-reordered json layer list according to layer-number
-removed unneeded pcell parameter in pcell test creation
=> Klayout PyCell integration

ihp-sg13g2/libs.tech/qucs/.gitignore, ihp-sg13g2/libs.tech/qucs/examples/ac_mim_cap.sch, ihp-sg13g2/libs.tech/qucs/examples/dc_diode_op.sch, ihp-sg13g2/libs.tech/qucs/examples/dc_hbt_13g2.sch, ihp-sg13g2/libs.tech/qucs/examples/resistors.sch, ihp-sg13g2/libs.tech/qucs/examples/symbols.sch, ihp-sg13g2/libs.tech/qucs/user_lib/IHP_PDK_basic_components.lib, ihp-sg13g2/libs.tech/qucs/user_lib/IHP_PDK_nonlinear_components.lib
Parameters added to the passive devices and diodes. 
Respective test cases created.
=> Updated basic and nonlinear symbol libraries, more examples added.

ihp-sg13g2/libs.tech/ngspice/models/resistors_mod.lib, ihp-sg13g2/libs.tech/xschem/sg13g2_pr/rhigh.sym, ihp-sg13g2/libs.tech/xschem/sg13g2_pr/rppd.sym, ihp-sg13g2/libs.tech/xschem/sg13g2_pr/rsil.sym, ihp-sg13g2/libs.tech/xschem/sg13g2_tests/dc_res_temp.sch
Support for number of bends "b" and parallel multiplier "m" added.  In resistors_mod.lib m parameter is also propagated
=> Resistor symbols for xschem modified, b and m parameters considered in the netlist

ihp-sg13g2/libs.tech/ngspice/openvaf/PSP103_SPCalculation.include, ihp-sg13g2/libs.tech/ngspice/openvaf/PSP103_macrodefs.include
Problem #64 solved. Changes in PSP implementation according to the code fixes provided by @metroid120
=> PSP model updated, Cgdsb glitch issue #64 resolved

ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/__init__.py, ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/rhigh_code.py, ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/rppd_code.py, ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/sg13g2_tech.json
Rhigh and rppd PCells were compared with original pdk, one difference was found: 
"HeatRes.drawing" - klayout
"HeatTrans.drawing" - orginal
=> Support for rppd and rhigh PCells added. Heat transfer layer name issue

.github/workflows/lvs_regression.yml, ihp-sg13g2/libs.tech/klayout/tech/lvs/README.md, ihp-sg13g2/libs.tech/klayout/tech/lvs/testing/README.md, ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_options.lym
Updates in the PR:
- Change the default values for switches for GUI run.
=> Change the default values for switches for GUI run

ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/sealring_code.py
Metal fill in the sealring was not DRC conform and should be handled by other tools.
=> libs.teck: klayout: pycell: Remove filler from Sealring

ihp-sg13g2/libs.tech/klayout/tech/lvs/rule_decks/layers_definitions.lvs
=> Remove NO_DRC filtering

ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/__init__.py, ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/dantenna_code.py, ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/dpantenna_code.py, ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/sg13g2_tech.json
dantenna and dpantenna PCells minimal integration. Options like get width from area input are not supported.
=> dantenna and dpantenna PCells integration

ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_maximal.lydrc, ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc, ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_density_report.lym
The current DRCs don't report fill correctly and generate violations for non-chip areas. This PR also includes @KrzysztofHerman script to report the density.
=> Update Filler Checks

.gitmodules, README.md
=> Added 'Digital' IHP130 cells as submodule

ihp-sg13g2/libs.tech/klayout/tech/lvs/rule_decks/custom_writer.lvs, ihp-sg13g2/libs.tech/klayout/tech/lvs/sg13g2_full.lylvs, ihp-sg13g2/libs.tech/klayout/tech/lvs/testing/Makefile
Updates:
- Update custom writer to match netlist units to meters as requested.
=> Updating LVS dumped netlist

ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_maximal.lydrc, ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc
- new options, increased accuracy of space and separation checks
- fixes incorrect DRC errors, e.g. for `pSD.d`, `pSD.d1`
=> Update KLayout DRC scripts

.gitmodules
Changed pypreprocessor submodule to ihp clone repo
=> PyCell Klayout integration

ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/__init__.py, ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/ihp/pypreprocessor.py
This pull request removes the dependency on psutil, which is difficult to install under Windows. It would have to be compiled with the same compiler as KLayout.
=> Improve Windows compatibility of PyCell code

ihp-sg13g2/libs.tech/klayout/python/sg13g2_pycell_lib/__init__.py
Reverts IHP-GmbH/IHP-Open-PDK#227
=> Revert "ihp-sg13g2: libs.tech: klayout: python: Move getProcessNames()"

ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_density_report.lym, ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_filler_ActGatP.lym, ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_filler_Metal.lym, ihp-sg13g2/libs.tech/klayout/tech/macros/sg13g2_filler_TopMetal.lym, ihp-sg13g2/libs.tech/klayout/tech/scripts/filler.py
This PR integrates filler scripts used for Nov'204 tape-out. The PR #255 will be removed.
=> Filler scripts hotfix to the main

ihp-sg13g2/libs.tech/xschem/sg13g2_pr/npn13G2v.sym, ihp-sg13g2/libs.tech/xschem/sg13g2_pr/npn13G2v_5t.sym, ihp-sg13g2/libs.tech/xschem/xschemrc
npn13G2v symbols updated in order to support `El` parameter. Also DRC rules updates for xschem
=> Xschem npn13G2v symbols updated 

ihp-sg13g2/libs.tech/klayout/tech/scripts/bondpad.py
Script to generate bondpads GDS files by passing the diameter and shape.
=> ihp-sg13g2: libs.tech: klayout: Add Script to Generate Bondpads

ihp-sg13g2/libs.tech/magic/ihp-sg13g2.tech
Related to #376 
cc @RTimothyEdwards
=> A couple of minor fixes to the magic tech file

ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_maximal.lydrc, ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc
- width check produced false positives for edges of different polygons
- fixes #416
=> Update KLayout DRC scripts: Fix bug in width checks

ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_maximal.lydrc, ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc
They now also check intersecting edges.
=> DRC: Update behavior of Mx.b checks

ihp-sg13g2/libs.tech/ngspice/models/resistors_mod.lib
Revised version of PR #476 by christoph-weiser, who found this serious problem in poly resistor calculation.
This PR fixes merge conflicts of PR #476 because of missing files.
=> removes double counting of poly resistors contact contribution

ihp-sg13g2/libs.tech/netgen/ihp-sg13g2_setup.tcl
Fixes #482
- [ O ] Tests pass
- [ O ] Appropriate changes (none needed) to README are included in PR
=> Corrected typo for cell2 reduction.

ihp-sg13g2/libs.tech/netgen/ihp-sg13g2_setup.tcl
Fixes #524 
- [O] Tests pass
- [?] Appropriate changes to README are included in PR -> no changes
=> Netgen setup hbt terminal swap fix

ihp-sg13g2/libs.ref/sg13g2_stdcell/cdl/sg13g2_stdcell.cdl
Pin order in CDL is fixed for following cells:
sg13g2_dfrbpq_1
sg13g2_dfrbpq_2
sg13g2_sdfrbpq_1
sg13g2_sdfrbpq_2
sg13g2_sdfrbp_1
sg13g2_sdfrbp_2.
=> Stdcell Update 2. Hot Fix 2.

ihp-sg13g2/libs.tech/ngspice/models/resistors_mod_mismatch.lib
This PR completes the PR #563 by adding 3rd node for mismatch resistor models.
=> complete 3rd node for resistor mismatch models

ihp-sg13g2/libs.tech/klayout/tech/sg13g2.map
* Remove all unused NAME layer names that were commented out.
* Align all layers properly with tabs to have them at the indentation.
I will update the `sg13g2.map` file in OpenROAD-Flow-Scripts afterwards.
=> ihp-sg13g2: libs.tech: klayout: Update sg13g2.map File

ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_maximal.lydrc, ihp-sg13g2/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc
=> DRC: Fix incompatibility with new KLayout v0.30.0
